### ISSUE TITLE
How to link multi angle video/view multi angle video in Clappr video player

### ISSUE THREAD

**Issue by Night-Crawle** [thiagopnts/clappr-video360#11]
Hi!,
I am very interesting with your plugin....I have tried to developed your plugin for multi angle view..
Do you have any idea..how it want to customize..html5 canvas/code..

Sample demo:  http://tronevr.esy.es/final-preview/

Note: this is not Clappr player..But i want to customize, as this with your plugin...Can you help for that...
Thanks! 
Dj

**Comment by thiagopnts** [comment]
Hi!
To achieve this I think you would need to implement a multi angle plugin for clappr first. Since 360 video plugin is transparent for playback then it would work with 360 and non 360 videos. I've done this in clappr a couple years ago and it was really straightforward, but unfortunately the plugin was not open source

**Comment by Night-Crawle** [comment]
Do you have plugin url

**Comment by thiagopnts** [comment]
Unfortunately no, it was used for a specific app and its not live anymore. I'll be closing this since its not a problem with the plugin itself
