### ISSUE TITLE
Is that possible to support vrvideo on mobile with Google Cardboard?

### ISSUE THREAD

**Issue by hughred22** [thiagopnts/clappr-video360#4]
Is that possible to support Google Cardboard on mobile safari or mobile chrome?

**Comment by thiagopnts** [comment]
In order to make it work on mobile we would need to use only canvas to build up the 360 scene, but last time I checked my current solution was too slow for that. I have some ideias to improve that so we can bring this experience to mobile web as well. About the Google Card board I still didn't get my hands on so I can't talk much, but it could be something interesting to play with.

**Comment by hughred22** [comment]
Are you using three.js and WebGL? Like

    renderer = new THREE.WebGLRenderer();

instead of using Canvas? What is your method? Thanks!

**Comment by thiagopnts** [comment]
Yes, I use the WebGLRenderer, when using the canvas renderer things get slow. Right now I split the current source into 6 frames(one for each angle) and store them in a temporary canvas, them I transform it in a cube's texture, so basically each angle is a texture in a cube. Once its playing I transform the cube into a sphere and put the user perspective inside it.

**Comment by sportexholdings** [comment]
Hi!,
I have tried your plugin:

http://opta360.com/360player-upgrade/

but video is not load...any idea what the issue is...

**Comment by thiagopnts** [comment]
[kaleidoscope](https://github.com/thiagopnts/kaleidoscope) supports android and iphone, but to bring the iphone support to this clappr plugin would require a bit more work, I'll not look into it now because iOS 10 will have support for inline videos so we can wait for it and have this implemented for free without adding complexity to the plugin
