### ISSUE TITLE
Hi!, your 360 plugin not working..

### ISSUE THREAD

**Issue by sportexholdings** [thiagopnts/clappr-video360#5]
Hi!,I have tried your plugin.but it's seems not working..only i can hear the sound...any idea...whats

> **wrong with my coding..**

Test Link: http://opta360.com/360player-upgrade/

Best,
Imesh

**Comment by thiagopnts** [comment]
Hi, this plugin doesn't support equirectangular videos, only cubemap transcoded https://github.com/facebook/transform
You would need to apply this facebook ffmpeg filter in order to make your shark video compatible.

I've been working on a library that supports equirectangular videos: https://github.com/thiagopnts/360viewer I'll update this plugin to support it as soon as I finish

**Comment by sportexholdings** [comment]
Hi!,Thanks! for quick response....
I have update it:
http://opta360.com/360player-upgrade/

http://opta360.com/360player-upgrade/video-preview.php

and how did i get work with ios 8.. i tried... ios 9 seems work. not sure...
and i also found,someone modified your js and get work with Android and iPad.. if yes... how do i modified the code for mobile view.. specially ipad.
Thank you.

https://github.com/thiagopnts/video-360/issues/3

**Comment by thiagopnts** [comment]
yes, the missing thing to work on android and ipad is to add touch event handlers. This doesn't work on iphone due some iOS restrictions related to video playback on the browser. The lib I've been working already supports it, so the next version of this plugin will support it out of the box. I should release it later next week. My plans for this next release are:

- support only equirectangular videos, so no more cubemap projections like facebook videos
- touch support so it can work on recent android versions and ipad
- support mobile devices accelerometer for 360 motion

**Comment by sportexholdings** [comment]
HI!,Thanks for your comment and feed back....and i am waiting to test new released of this plugin... By the way,I need help for implement ,multiple plugins.I made demo.but it's not work.can you checked and tell me..what i missed there in my coding...

Link: http://opta360.com/360player-upgrade/test-new.php

**Comment by me-vlad** [comment]
missing comma after
markersPlugin: {)

**Comment by sportexholdings** [comment]
Thanks for both of you..  :+1:

**Comment by sportexholdings** [comment]
Hi!, is your new plugin ready...
waiting to test it..
also, i hope this will help you for future development.
Link: http://yanwsh.github.io/videojs-panorama/

**Comment by thiagopnts** [comment]
I've been busy with some other things and I'm still working on my 360 library so I can rewrite this plugin. This videojs plugin looks great, thanks for sharing!

**Comment by sportexholdings** [comment]
Hi!,Thanks for response...my friend..i have issue with get work pre-roll ads.
recently I am trying to setup simple pre-roll video or vast feed pre roll before the video start using clappr video player.i have tried,many times..but any of attempts not succeed.so,i am looking help from you. i hope you can help me...
Kindly regards!,
Sam

some thing similar to this:
<script>
Clappr('example_video_1', {}, function(){ 
  var player = this;
  player.preroll({
    src:"advertisement.mp4"
  });
});
</script>

sample link:  https://github.com/dirkjanm/videojs-preroll

**Comment by thiagopnts** [comment]
I released a new version of the 360 plugin, it should work with equirectangular videos, it also has touch support and control over device orientation, tested on a Nexus 4.

Regarding the preroll plugin, I think your code wouldn't work because the way clappr's plugin works is different than videojs, you should follow this example: https://github.com/clappr/clappr/wiki/Our-first-plugin
